name: HTTP-Server-Simple-Mason
version: 0.06
abstract: A simple mason server
author: Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
requires:
  HTTP::Server::Simple: 0.04
  HTML::Mason: 1.25
  Hook::LexWrap: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
