--- 
abstract: A simple mason server
author: 
  - Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-Server-Simple-Mason
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Mason: 1.25
  HTTP::Server::Simple: 0.04
  Hook::LexWrap: 0
version: 0.10
